# Use a lightweight base image
FROM alpine:latest

# Install SQLite
RUN apk add --no-cache sqlite

# Create a directory for the SQLite database
RUN mkdir /data

# Set the working directory
WORKDIR /data

# Copy the SQLite database file to the container
COPY database.db .

# Expose the SQLite port (optional)
EXPOSE 3306

# Set the command to run when the container starts

CMD ["/usr/bin/sqlite3", "database.db"]